### ISSUE TITLE
BaseComponent NoClassDefFoundError

### ISSUE THREAD

**Issue by DoubleDeltas** [DoubleDeltas/MineCollector#11]
```
[Mcol] Enabling MineCollector v1.1.0
[15:47:59] [Server thread/ERROR]: Error occurred while enabling MineCollector v1.1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
        at com.doubledeltas.minecollector.data.DataManager.loadData(DataManager.java:44) ~[?:?]
        at com.doubledeltas.minecollector.MineCollector.onEnable(MineCollector.java:31) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[bukkit-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[bukkit-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[bukkit-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:519) ~[craftbukkit-1.19.4-R0.1-SNAPSHOT.jar:3682-Bukkit-dbc32ff]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:445) ~[craftbukkit-1.19.4-R0.1-SNAPSHOT.jar:3682-Bukkit-
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:581) ~[craftbukkit-1.19.4-R0.1-SNAPSHOT.jar:3682-Bukkit-dbc32ff]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:406) ~[craftbukkit-1.19.4-R0.1-SNAPSHOT.jar:3682-Bukkit-dbc32ff]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:237) ~[craftbukkit-1.19.4-R0.1-SNAPSHOT.jar:3682-Bukkit-dbc32ff]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954) ~[craftbukkit-1.19.4-R0.1-SNAPSHOT.jar:3682-Bukkit-dbc32ff]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:296) ~[craftbukkit-1.19.4-R0.1-SNAPSHOT.jar:3682-Bukkit-dbc32ff]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[bukkit-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[bukkit-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 13 more
```

**Comment by DoubleDeltas** [comment]
Spigot이 아닌 버킷을 사용한 오류. wontfix.
